language: python

jobs:
  include:
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: linux
      python: 3.8
    - os: osx
      language: generic
      python: 3.6
      osx_image: xcode11.4

cache: pip

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda create -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  # Pin R to 3.6.3 for now
  - conda install -c conda-forge r-base=3.6.3 r-rmarkdown r-ggplot2 r-plotly pandoc
  # Install regex through conda to avoid issues with Mac wheels
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      conda install -c conda-forge regex;
    fi
install:
  - pip install pycodestyle
  - pip install .[all]

script:
  - bash run_tests.sh

# Deploy to pypi automatically from tagged releases on the stable branch
deploy:
  provider: pypi
  user: __token__
  password:
   secure: t0faW2l8NlvdSXZrlo4ymdY4nDA0JMB2GrN+XmXbTyv9bnNZZ5b3iK+sg1D17DACOgD8adxPAPs8WQgwxc5tIXm7Q0aqgC07qTK0YRs4k8wJVPOh24MXYXKZxEq0UQ+s9ITpwJGITXL/89iSKSTiJ3fG3ANKjbNVHWHO8zNTEJ21bpB/gKP8omgtD8oTOX2EJmddkWSq6aSUtlb+lRqjKG86Xpub5gYW5tFIv+L1HYJnqCWycLz3knSM3CzDzJdKVi+2JpCchbkJqgaFvEDqBzva6iCdcwwkXK5KuSEX1jJM1uTsf74tugq8weDdX/EI+RmbOnd2j7ZFJw6/lz+5BjBTwEg3zCS4Eyxdb2uB16OKwBRouXjeP4f5O8Wea/PVt56OvBT4zfrpPaTWls28DghOPVLJDwbQalWLeH7Rk5eSaUzZnhxSObqYg2en9qgAlPM7eCDd8ay8lPPX6vPADe5eUpHHs+28uQ0ecwblH/XfI8mizIgRUIfcqAc2XPJnoYw2itA0ds9Rzk/yJbXDIrWgP+0tYh2dyH9aGRbW1/kGFdSK5N5paoSmcRYcYa7bfINcWw+VoOpk7GzbE8UnM4xFoubheuXA7gVP/XU12gkJBBKFAuydSRRz2nRwIz6YiFYrRBpzcnZlZ0cabGv79HpD/gDSOj7S0cx/jdwzHLU=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: airbnb/knowledge-repo
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
